name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }} ${{ matrix.ABI }} BUILD_PARI=${{ matrix.BUILD_PARI }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.13
          - stable-4.12
          - stable-4.11
        ABI: ['']
        BUILD_PARI:
          - 'yes'
          - 'no'
        include:
          - gap-branch: master
            ABI: 32
            BUILD_PARI: 'yes'

    steps:
      - uses: actions/checkout@v4
      - name: 'Install additional dependencies'
        run: |
          if [ "${{matrix.BUILD_PARI}}" = "yes" ]; then
            echo "BUILD_PARI=yes" >> $GITHUB_ENV
          else
            if [ "${{matrix.ABI}}" = "32" ]; then
              sudo apt-get install libpari-dev:i386
            else
              sudo apt-get install libpari-dev
            fi
          fi
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
      - uses: gap-actions/build-pkg@v1
        with:
          ABI: ${{ matrix.ABI }}
      - uses: gap-actions/run-pkg-tests@v2
      - uses: gap-actions/run-pkg-tests@v2
        with:
          only-needed: true
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v3

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gap-actions/setup-gap@v2
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v4
        with:
          name: manual
          path: ./doc/manual.pdf
          if-no-files-found: error
